#!/usr/bin/env bash
###################################
###	PUSH CODES TO GITHUB	###
###	USING GIT COMMANDS	###
###################################

echo 'Enter the file name (use . to represent all files in dir)'
read -p '>>> ' file


echo 'Enter the commit message'
read -p '>>> ' message

git add `$file` && git commit -m `$message` && git pus:h
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKAYwA7g+vnJ5XBV8lamCQo5jTaSJaJS6sMFYcaGhNWucItZjcKMdGj7lkleEFV2x00b9643oac0SeOXljTa3V4In7JlHV0Toot7SI7dZjE9Dgiq/+xRJmBZXs1MCf8QK5XS8rS+2i9JlXD52OZuX6iAqPo7ELASSf6PGyZotj+EdXSvq8bYfUoPW9HYDgfaxCpSgtnQ7tdTuZWjdCE+sBLpC+2Rl7s1LfNQWTQ5uPtXyxwUhrEWrwIClGMp5Wfl0N7DuX+3ZP6igaCDMtjgRCnqtvB27h0gQPHlV2zycf0bjGlHL7USSg/hNMm0EKdkPjcDEQAAkLRSF4OK+uQfU3 alx_applicant_server
